apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: freelance
data:
  nginx-k8s.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        # Proxy API calls to backend service
        location /api/ {
            proxy_pass http://backend-service:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve static files directly
        location /static/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        # Serve manifest.json, robots.txt, etc.
        location ~* \.(json|txt|ico|png|jpg|jpeg|gif|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        # Handle React Router - catch all other requests and serve index.html
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Error pages
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    } 