version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: freelance-jenkins
    network_mode: host
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ../:/workspace:rw
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    user: root
    privileged: true

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge 