apiVersion: v1
kind: ConfigMap
metadata:
  name: freelance-config
  namespace: freelance
data:
  # Database Configuration
  POSTGRES_DB: "freelancer_db"
  POSTGRES_USER: "freelancer_user"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/freelancer_db"
  SPRING_DATASOURCE_USERNAME: "freelancer_user"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  
  # MinIO Configuration
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_ACCESS_KEY: "iRb4jDOLKvmbfkQ"
  MINIO_BUCKET_NAME: "freelancer-cvs"
  
  # Mail Configuration
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_MAIL_HOST: "mailhog"
  SPRING_MAIL_PORT: "1025"
  SPRING_MAIL_USERNAME: ""
  SPRING_MAIL_PASSWORD: ""
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
  SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"
  
  # Security Configuration for Development
  SPRING_SECURITY_CSRF_DISABLED: "true"
  CORS_ALLOWED_ORIGINS: "http://freelance.local,http://localhost:3000"
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"

---
apiVersion: v1
kind: Secret
metadata:
  name: freelance-secrets
  namespace: freelance
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: ZnJlZWxhbmNlcl9wYXNz  # freelancer_pass
  MINIO_SECRET_KEY: T3NrYk1TU0ZMb0t3NDFk      # OskbMSsFLoKw41d
  MINIO_ROOT_USER: aVJiNGpET0xLdm1iZmtR        # iRb4jDOLKvmbfkQ  
  MINIO_ROOT_PASSWORD: T3NrYk1TU0ZMb0t3NDFk    # OskbMSsFLoKw41d 