apiVersion: v1
kind: ConfigMap
metadata:
  name: freelance-config
  namespace: freelance
data:
  # Database Configuration - Corrected service names
  POSTGRES_DB: "freelancer_db"
  POSTGRES_USER: "freelancer_user"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/freelancer_db"
  SPRING_DATASOURCE_USERNAME: "freelancer_user"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  
  # MinIO Configuration - Corrected service name
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_ACCESS_KEY: "iRb4jDOLKvmbfkQ"
  MINIO_BUCKET_NAME: "freelancer-cvs"
  
  # Mail Configuration - Corrected service name
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_MAIL_HOST: "mailhog-service"
  SPRING_MAIL_PORT: "1025"
  SPRING_MAIL_USERNAME: ""
  SPRING_MAIL_PASSWORD: ""
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
  SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"
  
  # Secrets are handled separately in secrets.yml
  # Ensure these keys match what the application expects
  # Example:
  # JWT_SECRET_KEY: defined-in-secrets
  # MINIO_SECRET_KEY: defined-in-secrets
  # POSTGRES_PASSWORD: defined-in-secrets