apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: freelance
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ergohubregistry.azurecr.io/freelance-frontend:latest  # Use Azure Container Registry
        imagePullPolicy: Always  # Always pull latest from ACR
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "https://ergohub.duckdns.org"  # Your DuckDNS domain
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: freelance
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 