---
- name: Deploy Freelance Platform to Minikube
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    namespace: "freelance"
    kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
  
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Apply ConfigMap and Secrets
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/configmap.yml
        state: present
        
    - name: Deploy PostgreSQL
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/postgres-deployment.yml
        state: present
        
    - name: Deploy MailHog
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/mailhog-deployment.yml
        state: present
        
    - name: Deploy MinIO
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/minio-deployment.yml
        state: present
        
    - name: Wait for infrastructure services to be ready
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - app in (postgres,mailhog,minio)
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_timeout: 300
        
    - name: Update backend deployment with new image (Minikube)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                - name: backend
                  image: "{{ backend_image | default('papadooo/freelance-backend:latest') }}"
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8080
                  envFrom:
                  - configMapRef:
                      name: freelance-config
                  - secretRef:
                      name: freelance-secrets
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "250m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
                  startupProbe:
                    httpGet:
                      path: /api/home
                      port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    failureThreshold: 30
                  livenessProbe:
                    httpGet:
                      path: /actuator/health
                      port: 8080
                    initialDelaySeconds: 60
                    periodSeconds: 30
                  readinessProbe:
                    httpGet:
                      path: /actuator/health
                      port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 10
        
    - name: Update frontend deployment with new image (Minikube)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend
            namespace: "{{ namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: frontend
            template:
              metadata:
                labels:
                  app: frontend
              spec:
                containers:
                - name: frontend
                  image: "{{ frontend_image | default('papadooo/freelance-frontend:latest') }}"
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "50m"
                    limits:
                      memory: "128Mi"
                      cpu: "100m"
                  livenessProbe:
                    httpGet:
                      path: /
                      port: 80
                    initialDelaySeconds: 30
                    periodSeconds: 30
                  readinessProbe:
                    httpGet:
                      path: /
                      port: 80
                    initialDelaySeconds: 10
                    periodSeconds: 10
        
    - name: Ensure backend service exists
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/backend-deployment.yml
        state: present
        
    - name: Ensure frontend service exists
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        src: ../kubernetes/frontend-deployment.yml
        state: present
        
    - name: Wait for application services to be ready
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ item }}"
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300
      loop:
        - backend
        - frontend
        
    # Optional: Deploy Ingress if you want to use it in Minikube
    # - name: Deploy Ingress
    #   kubernetes.core.k8s:
    #     kubeconfig: "{{ kubeconfig_path }}"
    #     src: ../kubernetes/ingress.yml
    #     state: present
        
    - name: Display deployment status
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
      register: pods
      
    - name: Show deployment summary
      debug:
        msg: |
          ✅ Minikube Deployment completed successfully!
          
          🐳 Images used:
          - Backend: {{ backend_image | default('papadooo/freelance-backend:latest') }}
          - Frontend: {{ frontend_image | default('freelance-frontend:latest') }}
          
          📊 Pod Status:
          {% for pod in pods.resources %}
          - {{ pod.metadata.name }}: {{ pod.status.phase }}
          {% endfor %}
          
          🌐 Access: Use minikube service frontend -n freelance 